language: clojure
lein: lein2
jdk:
- openjdk7
install: lein uberjar
script: lein midje
env:
  secure: "ae78SqIiUV9Qh7dOJyNysV4qy2fqTN9lAC730JKcvdvtUmYqgNrBwEMcLxXV5C5FZ+Eh4JrFP+VGfpuAwR7NlSPCnvFTT9lfBDm6PnhncZkAm4gKG/lN9kcmv1pOthXHzhY6wtldkBOctW1BNblvZXna29akGdpLV7RaS280J/k="
