language: clojure
lein: lein2
jdk:
- openjdk7
install: lein uberjar
script: lein midje
env:
  secure: UXo7WTdT89eg+83qbxtntNcD9DGWPJnPflagbfFaaLLzrvB8+9rGsEa3PHPzDZXZL0O7iAYsgEPdfk1HfmEN7gx4qfhWq4I6j8UdbjnOajs+cnukuCuxhUy3o/l0wqXb7vQUb4qfG/wWifRzQ9K7KFKyYqi6KaQon0+7IfI6gFk=
