language: clojure
lein: lein2
jdk:
- openjdk7
install: lein uberjar
script: lein midje
env:
  - secure: T/IhDL1pTnE34x+4D96MTEt3TeDMPCIGc74VM3vt9qVhK6hEhZtkHZFDcEx9p0JGxJgwyVlUgiZFtlHZgXXcLYfcuEenSFsxknhvViVXJgCVcY7aFZqQRXtYKNzj6qDT0zg6zPLpi4qHnQ7YqzhlfBqbo4+dr73g8sUZG5ktohU=
  - secure: PssjNK8QDJZn60PEUwoBubLFNTJoGTLVBZMKE26ngWdeABH//Nszv85ejbxrJf0keZqmufqNkdwaAR/cBdbhpgj5A+GrHdLDow35h/qsHYg8AGcqmDzYh15LnzAZ5rcJ9MRo0DEwN4fG/AuG4ZS+yj+D7fGjNLYvcXmtPPwbPnk=
